# Generated by Django 5.2.17 on 2026-09-19 18:51

import django.core.validators
import django.db.models.deletion
import lms.models
import lms.validators
from django.conf import settings
from django.db import migrations, models


def validate_legacy_grades(apps, schema_editor):
    alias = schema_editor.connection.alias
    Assignment = apps.get_model("lms", "Assignment")
    Feedback = apps.get_model("lms", "Feedback")
    bad = list(Feedback.objects.using(alias).filter(
        models.Q(grade__gt=1000) | models.Q(grade__gt=models.F("submission__assignment__max_points"))
    ).values_list("pk", flat=True)[:20])
    if bad or Assignment.objects.using(alias).filter(max_points__gt=1000).exists():
        raise RuntimeError(
            f"Legacy grades/maximums violate limits (Feedback IDs: {bad}). "
            "Run audit_legacy_data, agree corrections with the teacher, and retry. "
            "No grades have been silently clamped. See docs/DEPLOYMENT.md."
        )


def preserve_attempts(apps, schema_editor):
    alias = schema_editor.connection.alias
    Submission = apps.get_model("lms", "Submission")
    Feedback = apps.get_model("lms", "Feedback")
    Event = apps.get_model("lms", "SubmissionEvent")
    for attempt in Submission.objects.using(alias).select_related("assignment").iterator(chunk_size=500):
        feedback = Feedback.objects.using(alias).filter(submission_id=attempt.pk).first()
        Submission.objects.using(alias).filter(pk=attempt.pk).update(
            max_points_snapshot=attempt.assignment.max_points,
            deadline_snapshot=attempt.assignment.deadline,
            review_revision=1 if feedback else 0,
        )
        event = Event.objects.using(alias).create(
            submission_id=attempt.pk, actor_id=attempt.student_id, action="submitted",
        )
        Event.objects.using(alias).filter(pk=event.pk).update(created_at=attempt.submitted_at)
        if feedback:
            decision = "needs_revision" if attempt.status == "needs_revision" else "checked"
            Feedback.objects.using(alias).filter(pk=feedback.pk).update(decision=decision)
            event = Event.objects.using(alias).create(
                submission_id=attempt.pk, actor_id=feedback.teacher_id, action="reviewed",
                decision=decision, grade=feedback.grade, comment=feedback.comment,
            )
            Event.objects.using(alias).filter(pk=event.pk).update(created_at=feedback.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_legacy_grades, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Отправлено'), ('reviewed', 'Проверка')], max_length=20)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие сдачи',
                'verbose_name_plural': 'История сдач и проверок',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_submission_per_student_assignment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='decision',
            field=models.CharField(choices=[('checked', 'Проверено'), ('needs_revision', 'На доработку')], default='checked', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='deadline_snapshot',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_points_snapshot',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='submission',
            name='review_revision',
            field=models.PositiveIntegerField(default=0, verbose_name='Версия проверки'),
        ),
        migrations.AddField(
            model_name='submission',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='material_file',
            field=models.FileField(blank=True, db_index=True, upload_to=lms.models.assignment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'm4a', 'ogg', 'aac', 'zip', 'rar', '7z']), lms.validators.validate_upload], verbose_name='Материалы задания'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='lms.assignment', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_answer',
            field=models.FileField(blank=True, db_index=True, upload_to=lms.models.submission_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'm4a', 'ogg', 'aac', 'zip', 'rar', '7z']), lms.validators.validate_upload], verbose_name='Файл ответа'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='text_answer',
            field=models.TextField(blank=True, max_length=20000, verbose_name='Текстовый ответ'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-submitted_at'], name='submission_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), ('grade__lte', 1000), _connector='OR'), name='feedback_grade_range'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('decision', 'needs_revision'), models.Q(('decision', 'checked'), ('grade__isnull', False)), _connector='OR'), name='feedback_decision_grade'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'assignment', 'version'), name='unique_submission_attempt'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='submission_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('max_points_snapshot__lte', 1000)), name='submission_points_range'),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.submission'),
        ),
        # Irreversible: collapsing multiple attempts would destroy history. Restore backups instead.
        migrations.RunPython(preserve_attempts),
    ]
