# Generated by Django 5.2.17 on 2026-09-19 20:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_versioned_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Навык')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('grammar', 'Грамматика'), ('vocabulary', 'Лексика'), ('listening', 'Аудирование'), ('speaking', 'Говорение'), ('writing', 'Письмо'), ('reading', 'Чтение')], default='grammar', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отложить публикацию до'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=20, verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='block',
            name='cefr_level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Начальный'), ('A2', 'A2 — Элементарный'), ('B1', 'B1 — Средний'), ('B2', 'B2 — Выше среднего'), ('C1', 'C1 — Продвинутый'), ('C2', 'C2 — В совершенстве')], max_length=2, verbose_name='Уровень CEFR'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('file', 'Файл'), ('audio', 'Аудио'), ('mixed', 'Текст + файл/аудио'), ('quiz', 'Тест с автопроверкой')], default='text', max_length=20, verbose_name='Тип ответа'),
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='lms.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Набор карточек',
                'verbose_name_plural': 'Наборы карточек (квизлеты)',
                'ordering': ['topic', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=300, verbose_name='Лицевая сторона')),
                ('back', models.CharField(max_length=300, verbose_name='Оборотная сторона')),
                ('example', models.CharField(blank=True, max_length=500, verbose_name='Пример')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='lms.flashcarddeck', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'Один правильный ответ'), ('multi', 'Несколько правильных ответов'), ('gap', 'Вписать ответ'), ('match', 'Установить соответствие')], default='mcq', max_length=10, verbose_name='Тип вопроса')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение к ответу')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Баллы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.assignment', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст')),
                ('match_text', models.CharField(blank=True, max_length=500, verbose_name='Вторая половина пары (для соответствия)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='lms.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимум')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Верных ответов')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Ответы по вопросам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempt', to='lms.submission', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='lms.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='AnswerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=20000, verbose_name='Черновик')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Сохранено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_drafts', to='lms.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Черновик ответа',
                'verbose_name_plural': 'Черновики ответов',
                'constraints': [models.UniqueConstraint(fields=('student', 'assignment'), name='unique_answer_draft_per_student')],
            },
        ),
        migrations.CreateModel(
            name='CommentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('code', models.CharField(blank=True, help_text='Например -s: вставка в комментарий по коду.', max_length=24, verbose_name='Короткий код')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст комментария')),
                ('is_shared', models.BooleanField(default=True, verbose_name='Общий для всех преподавателей')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_snippets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон комментария',
                'verbose_name_plural': 'Банк комментариев',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('author', 'code'), name='unique_snippet_code_per_author')],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease', models.FloatField(default=2.5, validators=[django.core.validators.MinValueValidator(1.3), django.core.validators.MaxValueValidator(3.5)])),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Повторить')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lms.flashcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Повторение карточки',
                'verbose_name_plural': 'Повторения карточек',
                'indexes': [models.Index(fields=['student', 'due_at'], name='card_review_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('card', 'student'), name='unique_card_review')],
            },
        ),
    ]
