# Generated by Django 5.2.17 on 2026-09-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_skill_assignment_publish_at_assignment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.JSONField(blank=True, default=list, verbose_name='Бейджи'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Серия дней'),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последний день активности'),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего XP'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cefr_level', models.CharField(blank=True, choices=[('A1', 'A1 — Начальный'), ('A2', 'A2 — Элементарный'), ('B1', 'B1 — Средний'), ('B2', 'B2 — Выше среднего'), ('C1', 'C1 — Продвинутый'), ('C2', 'C2 — В совершенстве')], max_length=2, verbose_name='Уровень CEFR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'student'}, related_name='student_groups', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Если указано, задание доступно только ученикам этой группы', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='lms.group', verbose_name='Группа'),
        ),
    ]
