# Generated by Django 5.2.17 on 2026-09-21 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_add_group_model_and_gamification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Если выбраны ученики, задание также будет доступно им персонально', related_name='assigned_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Индивидуально для учеников'),
        ),
    ]
