# Generated by Django 5.2.17 on 2026-09-22 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_add_assignment_assigned_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_decks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец личного словаря'),
        ),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='lms.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Один правильный ответ'), ('multi', 'Несколько правильных ответов'), ('gap', 'Вписать ответ'), ('match', 'Установить соответствие'), ('order', 'Предложение из слов'), ('sort', 'Сортировка по колонкам'), ('spell', 'Слово из букв')], default='mcq', max_length=10, verbose_name='Тип вопроса'),
        ),
    ]
