# Generated by Django 5.2.17 on 2026-09-23 11:49

import django.core.validators
import django.db.models.deletion
import lms.models
import lms.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_flashcards_become_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_retake',
            field=models.BooleanField(default=False, help_text='После завершения ученик может начать задание с чистого листа.', verbose_name='Можно пройти заново'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_tries',
            field=models.PositiveSmallIntegerField(default=3, help_text='Сколько раз ученик может ответить на пункт с автопроверкой.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Попыток на пункт'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='recording_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальная длительность аудиоответа. Пусто — без лимита.', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)], verbose_name='Лимит записи, секунд'),
        ),
        migrations.AddField(
            model_name='question',
            name='recording_limit_seconds',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(600)], verbose_name='Лимит записи, секунд'),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Один правильный ответ'), ('multi', 'Несколько правильных ответов'), ('gap', 'Вписать ответ'), ('match', 'Установить соответствие'), ('order', 'Предложение из слов'), ('sort', 'Сортировка по колонкам'), ('spell', 'Слово из букв'), ('text', 'Свободный ответ (проверяет преподаватель)'), ('voice', 'Голосовой ответ (проверяет преподаватель)')], default='mcq', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='Проход')),
                ('state', models.CharField(choices=[('open', 'Есть попытки'), ('correct', 'Верно'), ('failed', 'Попытки исчерпаны'), ('answered', 'Ответ принят')], default='open', max_length=10, verbose_name='Состояние')),
                ('tries', models.JSONField(blank=True, default=list, verbose_name='Попытки')),
                ('text_answer', models.TextField(blank=True, max_length=20000, verbose_name='Текст ответа')),
                ('file_answer', models.FileField(blank=True, db_index=True, upload_to=lms.models.response_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'm4a', 'ogg', 'aac', 'zip', 'rar', '7z']), lms.validators.validate_upload], verbose_name='Запись ответа')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы автопроверки')),
                ('teacher_points', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='lms.assignment', verbose_name='Задание')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='lms.question', verbose_name='Пункт')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='lms.submission', verbose_name='Сдача')),
            ],
            options={
                'verbose_name': 'Ответ на пункт',
                'verbose_name_plural': 'Ответы на пункты',
                'ordering': ['round', 'question__order', 'question_id'],
                'indexes': [models.Index(fields=['student', 'assignment', 'round'], name='response_round_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'question', 'round'), name='unique_question_response_round')],
            },
        ),
    ]
