# Generated by Django 5.2.17 on 2026-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_item_checks_and_recording_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='exam_mode',
            field=models.BooleanField(default=False, help_text='Одна попытка на пункт, без ✓/✗ и правильных ответов до завершения задания. Разбор ученик увидит после того, как ответит на все пункты.', verbose_name='Режим контрольной'),
        ),
    ]
