# Generated by Django 5.2.17 on 2026-09-30 19:54

import django.core.validators
import django.db.models.deletion
import lms.models
import lms.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_feedback_audio_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAudioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to=lms.models.feedback_audio_comment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'rtf', 'odt', 'xls', 'xlsx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'm4a', 'ogg', 'aac', 'zip', 'rar', '7z']), lms.validators.validate_upload], verbose_name='Запись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Голосовой комментарий',
                'verbose_name_plural': 'Голосовые комментарии',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField(verbose_name='Начало (символ)')),
                ('end', models.PositiveIntegerField(verbose_name='Конец (символ)')),
                ('quote', models.TextField(max_length=4000, verbose_name='Выделенный текст')),
                ('comment', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('source', models.CharField(choices=[('teacher', 'Преподаватель'), ('ai', 'ИИ-проверка')], default='teacher', max_length=10, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий к фрагменту ответа',
                'verbose_name_plural': 'Комментарии к фрагментам ответа',
                'ordering': ['start', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='feedback',
            name='feedback_decision_grade',
        ),
        migrations.AddField(
            model_name='feedbackaudiocomment',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_comments', to='lms.feedback', verbose_name='Проверка'),
        ),
        migrations.AddField(
            model_name='feedbackhighlight',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='lms.feedback', verbose_name='Проверка'),
        ),
        migrations.AddConstraint(
            model_name='feedbackhighlight',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='highlight_end_after_start'),
        ),
    ]
