# Generated by Django 5.2.17 on 2026-10-01 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0014_feedbackaudiocomment_feedbackhighlight_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="excluded_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать назначение этих групп с верхнего уровня",
                related_name="excluded_from_assignments",
                to="lms.group",
                verbose_name="Исключённые группы",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="excluded_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать доступ этих учеников с верхнего уровня",
                limit_choices_to={"profile__role": "student"},
                related_name="excluded_from_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исключённые ученики",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="excluded_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать назначение этих групп с верхнего уровня",
                related_name="excluded_from_%(class)ss",
                to="lms.group",
                verbose_name="Исключённые группы",
            ),
        ),
        migrations.AddField(
            model_name="block",
            name="excluded_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать доступ этих учеников с верхнего уровня",
                limit_choices_to={"profile__role": "student"},
                related_name="excluded_from_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исключённые ученики",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="excluded_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать назначение этих групп с верхнего уровня",
                related_name="excluded_from_%(class)ss",
                to="lms.group",
                verbose_name="Исключённые группы",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="excluded_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать доступ этих учеников с верхнего уровня",
                limit_choices_to={"profile__role": "student"},
                related_name="excluded_from_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исключённые ученики",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="excluded_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать назначение этих групп с верхнего уровня",
                related_name="excluded_from_%(class)ss",
                to="lms.group",
                verbose_name="Исключённые группы",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="excluded_students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Не наследовать доступ этих учеников с верхнего уровня",
                limit_choices_to={"profile__role": "student"},
                related_name="excluded_from_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исключённые ученики",
            ),
        ),
    ]
