# Generated by Django 5.2.17 on 2026-10-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0015_assignment_excluded_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEventReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=100, verbose_name="Событие")),
                ("shown_at", models.DateTimeField(auto_now_add=True, verbose_name="Показано")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ui_event_receipts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Показ интерфейсного события",
                "verbose_name_plural": "Показы интерфейсных событий",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "event_key"),
                        name="unique_ui_event_receipt",
                    )
                ],
            },
        ),
    ]
