# Generated by Django 5.2.17 on 2026-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_usereventreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattachment',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название материала'),
        ),
    ]
